/*                                                                                                                                                                                                          
Author: Daniel Thompson                                                                                                                                                                                     
Course: CS 315                                                                                                                                                                                              
Assignment: Lab 4 Part C                                                                                                                                                                                    
*/                                                                                                                                                                                                          
                                                                                                                                                                                                            
using namespace std;                                                                                                                                                                                        
#include <iostream>                                                                                                                                                                                         
#include "TreeNode.hpp"                                                                                                                                                                                     
#include "BinSearchTree.hpp"                                                                                                                                                                                
                                                                                                                                                                                                            
int main( int argc, char *argv[] ) {                                                                                                                                                                        
  // create a tree and then print the values of its nodes                                                                                                                                                   
  // from the smallest to the largest.                                                                                                                                                                      
                                                                                                                                                                                                            
  BinSearchTree *tree = new BinSearchTree();                                                                                                                                                                
  BinSearchTree *bst = new BinSearchTree();                                                                                                                                                                 
  int v;                                                                                                                                                                                                    
                                                                                                                                                                                                            
  //Manual inserts into second tree                                                                                                                                                                         
  bst->insert(20);                                                                                                                                                                                          
  bst->insert(15);                                                                                                                                                                                          
  bst->insert(17);                                                                                                                                                                                          
  bst->insert(14);                                                                                                                                                                                          
  bst->insert(25);                                                                                                                                                                                          
  bst->insert(22);                                                                                                                                                                                          
  bst->insert(26);                                                                                                                                                                                          
                                                                                                                                                                                                            
                                                                                                                                                                                                            
  while( std::cin >> v ) {                                                                                                                                                                                  
    tree->insert( v );                                                                                                                                                                                      
  }                                                                                                                                                                                                         
                                                                                                                                                                                                            
  //Identical function                                                                                                                                                                                      
  if(tree->areIdentical(bst))                                                                                                                                                                               
    cout << "The trees are Identical\n";                                                                                                                                                                    
  else                                                                                                                                                                                                      
    cout << "Not identical\n";                                                                                                                                                                              
                                                                                                                                                                                                            
                                                                                                                                                                                                            
                                                                                                                                                                                                            
  cout<< "Intersect: \n";                                                                                                                                                                                   
  tree->intersectWith(bst)->inorderDump();                                                                                                                                                                  
                                                                                                                                                                                                            
  cout<< "Difference: \n";                                                                                                                                                                                  
  tree->differenceOf(bst)->inorderDump();                                                                                                                                                                   
                                                                                                                                                                                                            
                                                                                                                                                                                                            
  cout<< "Union: \n";                                                                                                                                                                                       
  tree->unionWith(bst)->inorderDump();                                                                                                                                                                      
                                                                                                                                                                                                            
  //cout<< "Difference: \n";                                                                                                                                                                                
  //tree->differenceOf(bst)->inorderDump();                                                                                                                                                                 
                                                                                                                                                                                                            
                                                                                                                                                                                                            
  //Prints out the entire tree in order. This is a large output done                                                                                                                                        
  // by using "make run" in the command line                                                                                                                                                                
  cout << "In order dump: \n";                                                                                                                                                                              
  tree->inorderDump();                           
   cout << endl;                                                                                                                                                                                             
                                                                                                                                                                                                            
  //Tests the size function                                                                                                                                                                                 
  cout <<"The size of the tree is: " <<  tree->size() << endl;                                                                                                                                              
                                                                                                                                                                                                            
  cout <<"Values at level: ";                                                                                                                                                                               
  tree->valuesAtLevel(1);                                                                                                                                                                                   
  cout << "\n";                                                                                                                                                                                             
                                                                                                                                                                                                            
  cout <<"Iter values at level ";                                                                                                                                                                           
  tree->iterValuesAtLevel(3);                                                                                                                                                                               
  cout << "\n";                                                                                                                                                                                             
                                                                                                                                                                                                            
  tree->levelOrderDump();                                                                                                                                                                                   
  cout << "Kth smallest: ";                                                                                                                                                                                 
  cout <<  tree->kthSmallest(3);                                                                                                                                                                            
  cout << endl;                                                                                                                                                                                             
                                                                                                                                                                                                            
  cout << "RtLsum: ";                                                                                                                                                                                       
  if(tree->hasRootToLeafSum(24) )                                                                                                                                                                           
    cout << "True\n";                                                                                                                                                                                       
  else                                                                                                                                                                                                      
    cout << "False\n";                                                                                                                                                                                      
                                                                                                                                                                                                            
  //Below are two cases each for Iterative and recursive find                                                                                                                                               
  //One to show it works if true, the other to show it works if false                                                                                                                                       
  if(tree->find(24507))                                                                                                                                                                                     
    cout <<  "Is a member\n";                                                                                                                                                                               
  else                                                                                                                                                                                                      
    cout << "Not a member\n";                                   
                                                                                                                                                                                                                
  if(tree->iterFind(24507))                                                                                                                                                                                 
    cout << "Is a member\n";                                                                                                                                                                                
  else                                                                                                                                                                                                      
    cout << "Not a member\n";                                                                                                                                                                               
                                                                                                                                                                                                            
  if(tree->iterFind(6))                                                                                                                                                                                     
    cout << "Is a member\n";                                                                                                                                                                                
  else                                                                                                                                                                                                      
    cout <<"Not a member\n";                                                                                                                                                                                
                                                                                                                                                                                                            
  if(tree->find(6))                                                                                                                                                                                         
    cout << "Is a member\n";                                                                                                                                                                                
  else                                                                                                                                                                                                      
    cout << "Not a member\n";                                                                                                                                                                               
                                                                                                                                                                                                            
                                                                                                                                                                                                            
  //Depth functions                                                                                                                                                                                         
  cout << "The Tree's depth is: " << tree->maxDepth() << "\n";                                                                                                                                              
  cout << "Iterative max depth: " << tree->iterMaxDepth() << "\n";                                                                                                                                          
                                                                                                                                                                                                            
  cout << "Level dump: \n";                                                                                                                                                                                 
  tree->levelOrderDump();                                                                                                                                                                                   
                                                                                                                                                                                                            
  delete bst;                                                                                                                                                                                               
  delete tree;                                                                                                                                                                                              
  return 0;                                                                                                                                                                                                 
}                                 
